# playbook.yml
- name: Install and bootstrap FluxCD on k3s
  hosts: k3s_node
  become: true
  vars:
    flux_repo_owner: Zamyza
    flux_repo_name: Hetzner3S
    flux_repo_branch: main
    flux_repo_path: clusters/my-cluster

  tasks:
    - name: Install Flux CLI
      shell: curl -s https://fluxcd.io/install.sh | bash
      args:
        creates: /usr/local/bin/flux

    - name: Add Flux to PATH for current session
      shell: echo 'export PATH=$PATH:/usr/local/bin' >> ~/.bashrc

    - name: Run flux bootstrap
      shell: |
        flux bootstrap github \
          --owner={{ flux_repo_owner }} \
          --repository={{ flux_repo_name }} \
          --branch={{ flux_repo_branch }} \
          --path={{ flux_repo_path }} \
          --personal
      environment:
        GITHUB_TOKEN: "{{ lookup('env', 'GITHUB_TOKEN') }}"