name: 'Terraform Setup'
description: 'Shared Terraform init and environment setup'
inputs:
  tf_version:
    required: true
  github_token_pat:
    required: true
  aws_access_key_id:
    required: true
  aws_secret_access_key:
    required: true
  working_directory:
    required: false
    default: ./terraform    

runs:
  using: "composite"
  steps:
    - name: Configure Git credentials for Terraform modules
      run: |
        git config --global url."https://x-access-token:${{ inputs.github_token_pat }}@github.com/".insteadOf "https://github.com/"
      shell: bash

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.tf_version }}

    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws_secret_access_key }}
      run: |
        terraform init -input=false \
          -backend-config="bucket=bucketofbuckets" \
          -backend-config="key=first_deployment/state/state.tfstate" \
          -backend-config="region=digitalocean" \
          -backend-config="endpoint=https://ams3.digitaloceanspaces.com" \
          -backend-config="skip_credentials_validation=true" \
          -backend-config="skip_metadata_api_check=true" \
          -backend-config="skip_region_validation=true" \
          -backend-config="skip_requesting_account_id=true" \
          -backend-config="use_path_style=true" \
          -backend-config="skip_s3_checksum=true"
      shell: bash
      working-directory: ${{ inputs.working_directory }}

