name: 'Deployment (Terraform -> Ansible)'
on:
    push: 
        branches:
            - main
            
permissions:
  contents: read                               

jobs:
    terraform-plan:
      runs-on: ubuntu-latest
      defaults:
        run: 
          working-directory: ./terraform
      steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Terraform Setup
            uses: ./.github/actions/terraform-setup
            with:
              tf_version: ${{ env.TF_VERSION }}
              github_token_pat: ${{ secrets.TF_GITHUB_TOKEN_PAT }}
              aws_access_key_id: ${{ secrets.TF_AWS_ACCES_KEY_ID }}
              aws_secret_access_key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}

          - name: plan
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCES_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
              HCLOUD_TOKEN: ${{ secrets.TF_HETZNER_TOKEN  }}
            run: |
              terraform plan
  
    terraform-apply:
      runs-on: ubuntu-latest
      needs: terraform-plan
      defaults: 
          run: 
              working-directory: ./terraform 
      steps:

          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Terraform Setup
            uses: ./.github/actions/terraform-setup
            with:
              tf_version: ${{ env.TF_VERSION }}
              github_token_pat: ${{ secrets.TF_GITHUB_TOKEN_PAT }}
              aws_access_key_id: ${{ secrets.TF_AWS_ACCES_KEY_ID }}
              aws_secret_access_key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}

          - name: Install Hcloud
            run: |
              curl -sSL https://github.com/hetznercloud/cli/releases/latest/download/hcloud-linux-amd64.tar.gz | tar -xz
              sudo mv hcloud /usr/local/bin/hcloud
              hcloud version
          
          - name: Apply
            env:
              AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_ACCES_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
              HCLOUD_TOKEN: ${{ secrets.TF_HETZNER_TOKEN  }}
            run: |
              terraform apply -auto-approve -input=false
