name: 'Terraform Deployment'
on:
    pull_request: 
        branches:
            - main
        types: [opened, synchronize, reopened]   
            
permissions:
  contents: read                               
  pull-requests: write                          

env:
  TF_VERSION: 1.11.4                            

jobs:
    terraform-plan:
        runs-on: ubuntu-latest
        defaults: 
            run: 
                working-directory: ./terraform 
        steps:

            - name: Terraform Setup
              uses: ./.github/actions/terraform-setup
              with:
                tf_version: ${{ env.TF_VERSION }}
                github_token_pat: ${{ secrets.TF_GITHUB_TOKEN_PAT }}
                aws_access_key_id: ${{ secrets.TF_AWS_ACCES_KEY_ID }}
                aws_secret_access_key: ${{ secrets.TF_AWS_SECRET_ACCESS_KEY }}
                hetzner_token: ${{ secrets.TF_HETZNER_TOKEN }}

            - name: Terraform Plan
              id: plan
              env: 
                HETZNER_TOKEN: ${{ secrets.TF_HETZNER_TOKEN }}
              run: |
                terraform plan -no-color -out=tfplan > plan.out

            - name: Comment Terraform Plan on PR
              uses: actions/github-script@v7
              with:
                github-token: ${{ secrets.GITHUB_TOKEN}}
                script: |
                    const fs = require('fs');
                    const plan = fs.redFileSync('plan.out', 'utf8')
                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `\`\`\`terraform\n${plan}\n\`\`\``
                        })
                        